#pragma once 

//#include "stm32g0xx.h"
// #include "core_cm4.h"
// #include "stm32g030xx.h"

// #include "stm32g0xx_hal.h"

// #include "stm32g0xx_ll_adc.h"
// #include "stm32g0xx_ll_bus.h"
// #include "stm32g0xx_ll_cortex.h"
// #include "stm32g0xx_ll_crc.h"
// #include "stm32g0xx_ll_dac.h"
// #include "stm32g0xx_ll_dma.h"
// #include "stm32g0xx_ll_exti.h"
// #include "stm32g0xx_ll_gpio.h"
// #include "stm32g0xx_ll_i2c.h"
// #include "stm32g0xx_ll_iwdg.h"
// #include "stm32g0xx_ll_pwr.h"
// #include "stm32g0xx_ll_rcc.h"
// #include "stm32g0xx_ll_rng.h"
// #include "stm32g0xx_ll_rtc.h"
// #include "stm32g0xx_ll_spi.h"
// #include "stm32g0xx_ll_system.h"
// #include "stm32g0xx_ll_tim.h"
// #include "stm32g0xx_ll_usart.h"
// #include "stm32g0xx_ll_usb.h"
// #include "stm32g0xx_ll_utils.h"
// #include "stm32g0xx_ll_wwdg.h"
